name: Push Original Text to Crowdin
on:
  workflow_call:

jobs:
  crowdin:
    name: Push Untranslated Documents to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      # - run: pnpm run crowdin:push  # TODO: Add a input of Crowdin token
      #   env:
      #     CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
