name: Build and Deploy GitHub Pages
on:
  workflow_call:
  schedule:
    - cron: 11 0/6 * * *
    - cron: 45 2/6 * * *
    - cron: 14 4/6 * * *

jobs:
  build:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn
      - run: yarn crowdin:pull
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v0
        with:
          path: ./build
  
  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
