on:
  push:
    branches:
      - main

jobs:
  crowdin:
    name: Push Untranslated Documents to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/yarn

      - run: yarn crowdin:push
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  trigger:
    needs: crowdin
    name: Trigger Webhook to Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger webhook use curl
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
