name: CI on Push
on:
  push:
    branches:
      - main

jobs:
  crowdin:
    name: Push Untranslated Documents to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: yarn
      - run: yarn crowdin:push
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  pages:
    needs: crowdin
    name: GitHub Pages
    uses: ./.github/workflows/github-pages.yml
